import numpy as np
from librosa import load
from scipy.io.wavfile import write


def convert(path):
    """Convert 32-bit PCM generated by librosa to 16-bit PCM.

    Arguments:
        path {str} -- path of the attack audio file
    """
    audio, _ = load(path=path, sr=16000)
    audio *= 32767
    audio = audio.astype(np.int16)
    write(filename=path, rate=16000, data=audio)
